name: ci

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'
    - name: Test
      run: |
        make test
